import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class AplikasiCekCuaca extends javax.swing.JFrame {
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane scrollPane;
    /**
     * Creates new form AplikasiCekCuaca
     */
    public AplikasiCekCuaca() {
        initComponents();
        dataTable = new JTable(new DefaultTableModel(new Object[]{"Kota", "Kondisi Cuaca"}, 0));
        scrollPane = new JScrollPane(dataTable);

                // Tambahkan ItemListener ke JComboBox untuk mendeteksi perubahan pilihan
        cbFav.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedCity = (String) cbFav.getSelectedItem();
                    kota.setText(selectedCity);  // Set kota text field dengan pilihan dari combo box
                    System.out.println("Kota favorit dipilih: " + selectedCity);
                }
            }
        });
    }
    private void updateWeatherIcon(String condition) {
    String iconPath = "/images/default.png";
    
    switch (condition.toLowerCase()) {
        case "clear":
        case "sunny":
            iconPath = "/images/sunny.png";
            break;
        case "rain":
        case "rainy":
        case "patchy rain nearby":
        case "showers":
        case "patchy light rain":
        case "moderate rain at times":
            iconPath = "/images/rainy.png";
            break;
        case "cloudy":
        case "overcast":
        case "partly cloudy":
            iconPath = "/images/cloudy.png";
            break;
        case "thunderstorm":
        case "patchy light rain with thunder":
        case "light rain shower":
        case "storm":
            iconPath = "/images/thunderstorm.png";
            break;
        default:
            iconPath = "/images/default.png";
            break;
    }
    
    icon.setIcon(new ImageIcon(getClass().getResource(iconPath)));
}
    private boolean kotaAdaDiComboBox(String kota) {
    for (int i = 0; i < cbFav.getItemCount(); i++) {
        if (cbFav.getItemAt(i).equalsIgnoreCase(kota)) {
            return true;
        }
    }
    return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kota = new javax.swing.JTextField();
        cekHasil = new javax.swing.JLabel();
        buttoncekcuaca = new javax.swing.JButton();
        buttonSFav = new javax.swing.JButton();
        buttonSdata = new javax.swing.JButton();
        buttonMdata = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        cbFav = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmuatdata = new javax.swing.JTable();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(214, 179, 175));

        cekHasil.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        cekHasil.setText("Kondisi Cuaca Sekarang :");

        buttoncekcuaca.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        buttoncekcuaca.setText("Cek Cuaca");
        buttoncekcuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncekcuacaActionPerformed(evt);
            }
        });

        buttonSFav.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonSFav.setText("Simpan Favorit");
        buttonSFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSFavActionPerformed(evt);
            }
        });

        buttonSdata.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonSdata.setText("Simpan Data");
        buttonSdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSdataActionPerformed(evt);
            }
        });

        buttonMdata.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonMdata.setText("Muat Data");
        buttonMdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMdataActionPerformed(evt);
            }
        });

        cbFav.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        cbFav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "makassar", "bandung", "batulicin" }));
        cbFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFavActionPerformed(evt);
            }
        });

        tblmuatdata.setFont(new java.awt.Font("Gill Sans MT", 0, 13)); // NOI18N
        tblmuatdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kota ", "Kondisi Cuaca"
            }
        ));
        jScrollPane1.setViewportView(tblmuatdata);

        btnkeluar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonSdata, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSFav)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMdata))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttoncekcuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cekHasil))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbFav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbFav)
                    .addComponent(kota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekHasil)
                .addGap(18, 18, 18)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(buttoncekcuaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSFav)
                    .addComponent(buttonMdata)
                    .addComponent(buttonSdata))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncekcuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncekcuacaActionPerformed
        // Ambil input kota dari JTextField atau dari pilihan JComboBox
        String city = kota.getText();
        
        // Panggil method getWeather dan ambil data cuaca
        String weatherCondition = CuacaClass.getWeather(city);
        
        // Tampilkan kondisi cuaca di JLabel
        cekHasil.setText("Kondisi Cuaca : " + weatherCondition);
        
        // Update gambar berdasarkan kondisi cuaca
        updateWeatherIcon(weatherCondition);
    }//GEN-LAST:event_buttoncekcuacaActionPerformed

    private void buttonSFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSFavActionPerformed
        String kotaFavorit = kota.getText();
        if (!kotaFavorit.isEmpty() && !kotaAdaDiComboBox(kotaFavorit)) {
            cbFav.addItem(kotaFavorit);
            System.out.println("Kota " + kotaFavorit + " ditambahkan ke favorit.");
        } else {
            System.out.println("Kota sudah ada di favorit atau input kosong.");
    }                                   
    }//GEN-LAST:event_buttonSFavActionPerformed

    private void buttonSdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSdataActionPerformed
        try (PrintWriter writer = new PrintWriter(new File("dataCuaca.csv"))) {
            writer.println("Kota, Kondisi Cuaca");
            String city = kota.getText();
            String weatherCondition = cekHasil.getText().replace("Kondisi Cuaca : ", "");
            writer.println(city + ", " + weatherCondition);
            JOptionPane.showMessageDialog(null, "Data cuaca berhasil disimpan ke CSV");
        } catch (Exception ex) {
            ex.printStackTrace();
    }                             
    }//GEN-LAST:event_buttonSdataActionPerformed

    private void buttonMdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMdataActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblmuatdata.getModel();

    try (BufferedReader br = new BufferedReader(new FileReader("dataCuaca.csv"))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (line.startsWith("Kota")) continue; // Skip header row

            String[] data = line.split(",");
            model.addRow(data); // Add data to the table without clearing it
        }
        JOptionPane.showMessageDialog(null, "Data berhasil dimuat dari CSV");
    } catch (Exception ex) {
        ex.printStackTrace();
    }                           
    }//GEN-LAST:event_buttonMdataActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void cbFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiCekCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton buttonMdata;
    private javax.swing.JButton buttonSFav;
    private javax.swing.JButton buttonSdata;
    private javax.swing.JButton buttoncekcuaca;
    private javax.swing.JComboBox<String> cbFav;
    private javax.swing.JLabel cekHasil;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kota;
    private javax.swing.JTable tblmuatdata;
    // End of variables declaration//GEN-END:variables
}
